# String Processing

### CHECKING STRING CONTENTS

#### To check if all the characters in a string are upper case

In [10]:
u = 'ABCDEF'
l = 'abcedf'

In [8]:
u.isupper()

True

In [12]:
l.isupper()

False

#### To check if all the characters in a string are lower case

In [15]:
u.islower()

False

In [17]:
l.islower()

True

#### To check if a string is in title case

In [21]:
s = 'A String'
w = ' \t\n'
c = 'ABCDEF'

In [23]:
s.istitle()

True

In [25]:
c.istitle()

False

#### To check if all the characters in a string are whitespace characters

In [28]:
w.isspace()

True

In [30]:
s.isspace()

False

#### To check if a string starts with a specified substring

In [33]:
s1 = 'A String'
s2 = 'A '
s3 = 'ng'

In [35]:
s1.startswith(s2)

True

In [37]:
s1.startswith(s3)

False

#### To check if a string ends with a specified substring

In [40]:
s1.endswith(s2)

False

In [42]:
s1.endswith(s3)

True

#### To check if a string contains only alphanumeric characters

In [45]:
s = 'Result:\t30'
a = 'ABCDEF'
n = '12345'

In [47]:
s.isalnum()

False

In [49]:
a.isalnum()

True

In [51]:
n.isalnum()

True

####  To check if a string contains only alphabetic characters

In [54]:
s = 'Result:\t30'
a = 'ABCDEF'
n = '12345'

In [56]:
s.isalpha()

False

In [58]:
a.isalpha()

True

In [60]:
n.isalpha()

False

#### To check if a string contains only numeric characters

In [63]:
f = '12.345'
a = 'ABCDEF'
n = '12345'

In [65]:
f.isnumeric()

False

In [67]:
a.isnumeric()

False

In [69]:
n.isnumeric()

True

## JOINING ITERABLES INTO A STRING

#### To join all items in a collection (iterable), call the join method on a string
representing the desired separator

In [74]:
colours = ['red','green','blue']
';'.join(colours)

'red;green;blue'

In [80]:
# Note that the elements of the collection must be strings

# numbers = [1,2,3,4,5]
# ' '.join(numbers)

# This will throw an error:
# TypeError: sequence item 0: expected str instance, int found

In [78]:
numbers = ['1','2','3','4','5']
' '.join(numbers)

'1 2 3 4 5'

## SPLITTING STRINGS

In [83]:
""" A string can be split into a list, with the split taking place on every occurrence
of a given character, as follows:
"""
s = 'Split this string into words'
print(s.split())

['Split', 'this', 'string', 'into', 'words']


## PARTITIONING STRINGS

In [90]:
"""
Similar to splitting a string, partitioning will break a string up into a three-
element tuple, containing:
• The part of the string before the first match;
• The first match; and
• The part of the string after the first match.
"""
s1 = 'This string will be partitioned into 3 strings'
s2 = s1.partition('partitioned')
print(s2)

('This string will be ', 'partitioned', ' into 3 strings')


## REPLACING STRINGS

In [95]:
"""
To replace every occurrence of a given substring within a string, we use the replace()
method. This takes two mandatory arguments, the first is the string that should be
matched and the second is the replacement string.
"""
s1 = 'An errror and another errror'
s2 = s1.replace('errror','error')
print(s2)

An error and another error


In [103]:
"""
We can use a third optional argument specify the number of replacements to make
"""
s1 = 'An errror and another errror'
s2 = s1.replace('errror','error',1) # Replace only first match
print(s2)

An error and another errror


## LEFT-JUSTIFYING STRINGS

In [106]:
"""
o left justify a string, padding the right hand side of the string with spaces, use
the ljust() method. The mandatory argument specifies the final width of the string
"""
s1 = 'Data Analytics'
s2 = s1.ljust(20)
s2

'Data Analytics      '

In [120]:
"""
Using a second (optional) argument, we can also specify a character to be used
for padding the string
"""
s1 = 'Data Analytics'
s2 = s1.ljust(20,'-')
print (f'{s2}, \ntotal num of char:{len(s2)}')

Data Analytics------, 
total num of char:20


## RIGHT-JUSTIFYING STRINGS

In [123]:
"""
To right justify a string, padding the left hand side of the string with spaces, use
the rjust() method. The mandatory argument specifies the final width of the string
"""
s1 = 'Data Analytics'
s2 = s1.rjust(20)
s2

'      Data Analytics'

In [125]:
"""
Using a second (optional) argument, we can also specify a character to be used
for padding the string
"""
s1 = 'Data Analytics'
s2 = s1.rjust(20,'-')
s2

'------Data Analytics'

## CENTERING STRINGS

In [128]:
"""
To centre a string, padding the both the left and right hand sides of the string with
spaces, use the center() method. The mandatory argument specifies the final width of
the string
"""
s1 = 'Data Analytics'
s2 = s1.center(20)
s2

'   Data Analytics   '

In [ ]:
"""
Using a second (optional) argument, we can also specify a character to be used for
padding the string
"""


In [130]:
s1 = 'Data Analytics'
s2 = s1.center(20,'-')
s2

'---Data Analytics---'

# BASIC FILE ACCESS - OPENING A FILE

The open() function returns a file object, otherwise known as a file handle, and takes
two arguments: filename and mode.
• The mode argument specifies how the file should be opened and takes one of the following values.
</br>
* r - the opened file can only be read from and not written to.
</br>
* w - the opened file can only be written to.
</br>
* a - the opened file can be written to with any new data being appended to the data already in the file.
</br>
* r+ - the opened file can be both read from and written to.
  </br>
* x - creates the specified file if it does not already exist and returns 
an error if the file exists.

In [146]:
"""
The write() writes the contents of string to the file, returning the number of characters
written.
• Other types of objects need to be converted, either to a string (in text mode) or a bytes object
(in binary mode), before writing them to the file.
"""
# value = ('the answer', 42)
# my_file.write(str(value))

'\nThe write() writes the contents of string to the file, returning the number of characters\nwritten.\n• Other types of objects need to be converted, either to a string (in text mode) or a bytes object\n(in binary mode), before writing them to the file.\n'

In [150]:
"""
• The tell() method is used to discover the current file position in a file stream. The current file
position can be altered with the seek() method.
"""
# f = open("myfile.txt", "r")
# print(f.tell())
# print(f.readline())
# print(f.tell())
# f.seek(f.tell()+2)
# print(f.tell())

'\n• The tell() method is used to discover the current file position in a file stream. The current file\nposition can be altered with the seek() method.\n'

In [152]:
"""
The tell() method is used to discover the current file position in a file stream:
"""
# f = open("myfile.txt", "r")
# print(f.tell())
# print(f.readline())
# print(f.tell())

'\nThe tell() method is used to discover the current file position in a file stream:\n'

In [156]:
"""
The current file position can be altered with the seek() method:
"""
# f.seek(f.tell()+2)
# print(f.tell())

'\nThe current file position can be altered with the seek() method:\n'

# FUNCTION

## THE YIELD KEYWORD

In [162]:
"""
* If we want our functions to return multiple values, for instance outputting
a value for each iteration through a for or while loop, the return keyword
is of no use to us. This is where the yield keyword comes in.
* The example below will output each row in turn, as soon as it has split
the row into columns:
"""
def csv_reader(file_name, file_mode, separator) :
    for row in open(file_name, file_mode) :
        yield row.split(separator)

## DEFAULT FUNCTION ARGUMENTS

In [169]:
"""
 In cases where a function can have sensible default values for one or more of
its parameters, it is possible to supply these defaults as part of the function
definition, avoiding the need to pass them each time the function is invoked.
* When a value is not specified for one of these arguments, the default value will
be used instead.
* The example function below will take a character string as an argument and
will either print it as is, or will print it in reverse.
"""
def newprint(text, how='asis') :
    if how == 'asis' :
        print(text)
    elif how == 'reverse' :
        print(text[::-1])
    else:
        raise ValueError("Invalid argument supplied for 'how' parameter")

In [171]:
newprint("Hello World")

Hello World


In [173]:
newprint("Hello World",how = 'reverse')

dlroW olleH


In [177]:
# newprint("Hello World",how = 'hide') # This will raise an error

## MUTABLE DEFAULT ARGUMENTS

In [190]:
"""
When using default arguments, you will need to pay special attention when
mutable objects are passed as defaults.
"""
def add_list_to_list(new_elements, to=[]) :
    to.extend(new_elements)
    return to

In [192]:
"""
As the default argument is an empty list, you might expect this code to return
a new list each time the add_list_to_list() function is invoked without supplying
the to argument. However, this is not what happens.
"""
list1 = add_list_to_list([1,2,3])
print(list1)

[1, 2, 3]


In [194]:
list2 = add_list_to_list([4,5,6])
print(list2)

[1, 2, 3, 4, 5, 6]


## VARIADIC FUNCTIONS

In [197]:
def send_message(message, *recipients) :
    for recipient in recipients :
        print(message+" "+recipient)


send_message('Hello','Hal','Frank')

Hello Hal
Hello Frank


In [199]:
"""
It is also possible to pass arbitrary arguments using a dictionary or key=value
format. This is achieved by putting two asterisks in front of the last parameter
in the parameter list and then passing in the values as if they were named
arguments.
"""
def say_hello(**recipients) :
    for recipient,greeting in recipients.items() :
        print('{0} {1}'.format(greeting,recipient))


say_hello(Hal='Hello',Frank='Good morning')

Hello Hal
Good morning Frank


## ANONYMOUS OR LAMBDA FUNCTIONS

* Inspired by the LISP language, a lambda function is an unnamed or
anonymous function that can have any number of parameters, but is
limited to one expression on a single line of code.
* A lambda function is an expression, and not a statement, and because of
this it can be used in parts of your code where a full function definition
would not be permitted, such as inside list comprehensions or the arguments of a function call.
* Unlike a regular function, a lambda expression will return automatically.
* Because it is limited to a single expression, it is less expressive than a full function definition. By its very nature, we can only squeeze so much logic into a lambda body.
* Lambda functions come into their own when used as an anonymous
function inside a regular function.
* For example, let’s assume that you have a function definition that takes
one argument for the parameter n, and that the value supplied to this
argument will be multiplied by an as yet unknown number.

In [204]:
def multiplier(n) :
    return lambda x : x * n

In [208]:
"""
The function definition returned by the multiplier function can now be
used, by supplying the values for the lambda argument x and giving them
an identifier.
"""
doubler = multiplier(2)
tripler = multiplier(3)

In [210]:
"""
The identifiers doubler and tripler can now be used as standalone
multiplication functions.
"""
print(doubler(10))

20


In [212]:
print(tripler(10))

30


## THE MAP FUNCTION

* The map function takes the name of a function and one or more iterable
objects (collections) as its arguments.
* It executes the function once for each item in the supplied collection(s)
returning the results of those function calls as a new collection.
* For example, consider the following loop-based code designed to replace a
each string in a list with its hash and then print the list of hashes

In [218]:
names = ['Mary', 'Isla', 'Sam']
for i in range(len(names)):
    names[i] = hash(names[i])

print(names)

[-7458212390406729208, -5917981613259530386, 8080066058617023836]


* The loop-based code in the previous slide can also be expressed as

In [221]:
names = ['Mary', 'Isla', 'Sam']
print(list(map(hash,names)))

[-7458212390406729208, -5917981613259530386, 8080066058617023836]


* <b>Note</b> that the <u>returned map</u> object must be cast <u>as a list.</u>
* This is because map uses lazy evaluation, where the returned values are
only computed when they are accessed.

## THE REDUCE FUNCTION

* Like the map function, the reduce function also takes a function name and
an iterable object as its arguments.
* It returns a value, usually a scalar, which is created by combining or
aggregating the items in the collection. The example below returns the
maximum value from a list of values
* Note that reduce() has now been moved out of the main Python
namespace and into the package functools.
* This is because there are better approaches to achieving the same
functionality, such as the use of list comprehensions.
* The reduce function can also be combined with operator functions such as
add() or mul() to achieve the same functionality as is provided by lambda
functions.

In [228]:
from functools import reduce
valuelist = [42, 123, 42, 3, 50]
print(reduce(lambda a,b : a if a > b else b, valuelist))

123


## THE FILTER FUNCTION

* Like map() and reduce(), the filter() function also takes a function and an
iterable object (such as a list) as arguments.
* It provides a simple and elegant way to filter elements in the iterable
object.
* The function passed in as an argument must return a Boolean value and
will be applied to each element in the iterable.
* Those elements for which the function returns True are returned by the
filter, those for which the function returns False are not.

In [232]:
"""
The example below filters a list of integers in the half open interval (10,31)
to return only those that are even.
"""
print(list(filter(lambda x: x % 2 == 0, range(10, 31))))

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


# INTERNET DATA

## WELL-KNOWN XML SCHEMATA

* Keyhole Markup Language (KML) is used to annotate geolocation data, and
is used on sites such as Google Maps.
* Mathematical Markup Language (MathML) is a way of including mathematical
equations in HTML pages and other documents. It produces similar results
to the equation environment in LATEX.
* RSS - Really Simple Syndication and Atom are both used to provide real-
time news feeds.
* The Resource Description Framework is used to describe and model the
information available from web resources.
* Scalable Vector Graphics (SVG) is used to define portable vector-based
images and animations that can be directly embedded in web pages.
* Closer to our own particular field, the Data Documentation Initiative (DDI)
is a standard for the production of machine-readable descriptions of
statistical data files, surveys and questionnaires, as well as any processing or
transformation carried out on these files.
* The Statistical Data and Metadata eXchange (SDMX) is an initiative to
achieve standardisation of the exchange of data between international and
supra-national bodies.

## SERIALISATION AND DESERIALISATION

* XML, along with JSON, is often used as serialisation format.
* Serialisation is the process of creating a file or stream-based representation
of an object in a program so that it can be transported to another system.
* Deserialisation is the process of converting the file or stream-based
representation back into an object within a program running on the remote
system.
* Serialisation/Deserialisation (frequently shortened to SerDes ) allows for
interaction between programs in a programming language-independent
manner.

## CREATING AN XML TREE IN PYTHON

In [242]:
import xml.etree.ElementTree as ET
data = '''<person>
<name>Chuck</name>
<phone type="intl">+1 734 303 4456</phone>
<email hide="yes"/>
</person>'''
tree = ET.fromstring(data)

In [244]:
print('Name:',tree.find('name').text)

Name: Chuck


In [246]:
print('Attr:',tree.find('email').get('hide'))

Attr: yes


## NAVIGATING AN XML TREE IN PYTHON

In [257]:
import xml.etree.ElementTree as ET
input = '''<data><users>
<user x="2"><id>001</id><name>Chuck</name></user>
<user x="7"><id>009</id><name>Brett</name></user>
</users></data>'''
xmldata = ET.fromstring(input)
userlist = xmldata.findall('users/user')
for user in userlist:
    print('Name', user.find('name').text)
    print('Id', user.find('id').text)
    print('Attribute', user.get("x"))
    print()


Name Chuck
Id 001
Attribute 2

Name Brett
Id 009
Attribute 7



## LOADING WEB RESOURCES

* The Python module urllib can be used to interact with resources accessible
through the internet.

In [261]:
import urllib.request
response = urllib.request.urlopen('http://python.org/')
html = response.read()
html = str(html)

* Polite crawlers should identify themselves using the User-Agent http header

In [264]:
request = urllib.request.Request('http://python.org/')
request.add_header("User-Agent", "My Python Crawler")
opener = urllib.request.build_opener()
response = opener.open(request) # make the http request

## CONSUMING WEB APIS

* The code below uses the urllib library to fetch a list of public APIs from an open API. The JSON
response is parsed to extract just the API names.
* Note that this API does not require authentication. Any API that requires authentication will
need additional code to handle that aspect of the communication.

In [280]:
import urllib.request
import json

# apis = []
# url = 'https://api.publicapis.org/entries'

# # Set the headers, including a User-Agent
# headers = {'User-Agent': 'Mozilla/5.0'}

# # Create the request with headers
# req = urllib.request.Request(url, headers=headers)

# # Open the URL and process the response
# with urllib.request.urlopen(req) as response:
#     parsed_json = json.loads(response.read())
#     for item in parsed_json['entries']:
#         apis.append(item['API'])

# # Print the specified range of APIs
# print(apis[30:34])



## LOADING WEB RESOURCES

* We can retrieve the status for the request and various metadata for the page,
such as the name of the server software and the content type of the returned
resource:

In [286]:
import urllib.request
respstring = 'The response code is {}'
servstring = 'The page is served by {}'
ctypestring = 'The page has the content type {}'
with urllib.request.urlopen('http://python.org/') as response:
    print(respstring.format(response.status))
    print(servstring.format(response.headers['Server']))
    print(ctypestring.format(response.headers['Content-Type']))

The response code is 200
The page is served by None
The page has the content type text/html; charset=utf-8


## WEB SCRAPING

Example using Beautiful Soup to extract data from Wikipedia

In [294]:
import urllib.request
from bs4 import BeautifulSoup
import pandas as pd

# Fetch the webpage
url = 'https://en.wikipedia.org/wiki/World_Happiness_Report'
web_page = urllib.request.urlopen(url)
parsed_data = BeautifulSoup(web_page, "html.parser")

# Find the table
table = parsed_data.find_all('table', {"class": "wikitable sortable"})[0]

# Initialize lists to store the data
rank, country, score = ([], [], [])

# Iterate through rows of the table
for row in table.findChildren('tr'):
    cells = row.findChildren('td')
    if len(cells) >= 3:  # Check for at least 3 columns to extract rank, country, score
        rank.append(cells[0].text.strip())    # Rank is in the 1st column
        country.append(cells[1].text.strip()) # Country is in the 2nd column
        score.append(cells[2].text.strip())   # Score is in the 3rd column

# Create the DataFrame
country_df = pd.DataFrame(rank, columns=['Rank'])
country_df['Country'] = country
country_df['Score'] = score

# Display the DataFrame
print(country_df)


    Rank       Country  Score
0      1     Lithuania  7.795
1      2        Israel  7.667
2      3       Iceland  7.658
3      4        Serbia  7.658
4      5       Denmark  7.598
..   ...           ...    ...
139  141      Zimbabwe  3.295
140  142         Congo  3.245
141  143  Sierra Leone  3.186
142  144       Lebanon  2.707
143  145   Afghanistan  1.721

[144 rows x 3 columns]


# EXCEPTIONS AND ASSERTIONS

## BUILT-IN EXCEPTIONS

* Python has built-in exceptions, for example:
* ZeroDivisionError - thrown when an arithmetic operation
involves a division by zero.
* MemoryError - thrown when a program runs out of memory
* OSError - thrown when an operating system error occurs, such
as when a file can not be opened, read from or written to.
* TypeError - thrown when an operation is applied to an object of
an incorrect type.
* See https://docs.python.org/3/library/exceptions.html for full details
of Python's built-in exceptions.

## TRY - EXCEPT CONSTRUCTS

In [303]:
# try :
#     statement block protected by exceptional handling
# except :
#     statement block to handle exceptions

In [309]:
# def getNumber():
#     isnumber = False
#     while not isnumber:
#         try:
#             num = float(input('Enter a number: '))
#             isnumber = True
#         except ValueError:
#             print('You did not enter a number. Try again!')
#     return num  # Return the valid number

# # Store the returned value in s
# s = getNumber()
# print("The number you entered is:", s)


In [311]:
try:
    filepath = './myfile.txt'
    with open(filepath, 'r') as fh:
        lines = fh.readlines()
except FileNotFoundError:
    print('The file {} was not found.'.format(filepath))
except IsADirectoryError:
    print('{} is a directory.'.format(filepath))
except PermissionError:
    print('Insufficient permissions to open {}.'.format(filepath))
else:
    for line in lines:
        print(line)


The file ./myfile.txt was not found.


#### OR

In [314]:
try:
    filepath = './myfile.txt'
    fh = open(filepath, 'r')
    lines = fh.readlines()
except FileNotFoundError:
    print('The file {} was not found.'.format(filepath))
else:
    for line in lines:
        print(line)
finally:
    # Ensure the file handle is closed if it was successfully opened
    if 'fh' in locals():
        fh.close()


The file ./myfile.txt was not found.


In [316]:
import urllib.request

try:
    response = urllib.request.urlopen('http://misspelledsite.com/')
except urllib.error.URLError as e:
    print('An error occurred when opening the URL:')
    print(str(e))


An error occurred when opening the URL:
<urlopen error [Errno -2] Name or service not known>


# REGULAR EXPRESSIONS

* Ken Thompson, creator of the UNIX operating system, defines a regular
expression as:
"... a pattern which specifies a set of strings of characters; it is said to
match certain strings."
* Regular expressions are sequences of characters used as patterns for
matching parts of strings.

## REGULAR EXPRESSION FUNCTIONS

In [321]:
"""
findall - returns a list containing all matches.
"""
import re
re.findall('\d','1 and 2 and 3')
['1', '2', '3']

['1', '2', '3']

In [327]:
"""
• search - returns the first match as a Match object.
Note: this example uses the special sequence \d, which will match any digit
character.
"""
import re
match = re.search('\d','And 1 and 2 and 3')
print(match)

<re.Match object; span=(4, 5), match='1'>


In [331]:
"""
• split - returns a list with the string split at each match
Note: this example uses the special sequence \s, which will
match any whitespace character
"""
import re
split = re.split('\s','Regular\texpressions are\npowerful')
print(split)

['Regular', 'expressions', 'are', 'powerful']


In [333]:
"""
• sub - replaces one or more matches with a new string
"""
import re
print(re.sub('or','and','A or B or C or D'))

A and B and C and D


## METACHARACTERS

* Metacharacters are characters in an expression that have a special meaning. [] square brackets are used to enclose a set of characters

In [338]:
import re
find = re.findall('[1,4,9]','1234568')
print(find)

['1', '4']


In [340]:
import re
find = re.findall('[a-c]','eafbgc')
print(find)

['a', 'b', 'c']


- ( . ) matches any single character.
- ( ^ ) matches the start of a string
- ( $ ) matches the end of a string
- ( * ) matches zero or more occurrences of a string or special character.
- ( + ) matches one or more occurrences of a string or special character.
- ( {} ) matches the exact number of occurrences of a string or special character.
- ( | ) matches either one or both of the strings or special characters on either side.
- ( \A ) - matches if the specified characters occur at the start of a string.
- ( \D ) - matches any character that is not a decimal digit.
- ( \w ) - Matches any word characters (alphanumeric characters) or the underscore.
- ( \b ) - matches a string or special character when it occurs at a word boundary

In [344]:
import re
find = re.findall('^..','The quick brown fox')
print(find)

['Th']


In [346]:
import re
find = re.findall('again$','Again and again and again')
print(find)

['again']


In [353]:
import re
find = re.findall('gan*','Again and again and again')
print(find)

['ga', 'ga', 'ga']


In [355]:
import re
find = re.findall('gai+','Again and again and again')
print(find)

['gai', 'gai', 'gai']


In [357]:
import re
find = re.findall('[l,o]{2}','We always watch football')
print(find)

['oo', 'll']


In [359]:
import re
s = 'We always watch football or cricket'
find = re.findall('always|football|cricket',s)
print(find)

['always', 'football', 'cricket']


In [361]:
import re
find = re.findall('\AThe','The quick brown fox. The lazy dog')
print(find)

['The']


In [363]:
import re
find = re.findall('\D','1 and 2 or 3')
print(find)

[' ', 'a', 'n', 'd', ' ', ' ', 'o', 'r', ' ']


In [365]:
import re
s = '!AabcC&_'
find = re.findall(r'\w',s)
print(find)

['A', 'a', 'b', 'c', 'C', '_']


In [367]:
import re
s = 'We always watch football or cricket'
find = re.findall(r'\bal',s)
print(find)

['al']


## CAPTURE GROUPS

* Capture groups are denoted by parentheses and are used to
group the regex enclosed within them. They capture matches for
the regex into numbered groups that can be extracted or used with a
numbered back-reference.
* The example below checks for the presence of an IP address and if
found, extracts each part of the dotted quad.

In [371]:
import re
ipregex = r'\b([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\b'
string = 'The IP address 192.168.1.1 is a class C address.'
match = re.findall(ipregex,string)
print(match)

[('192', '168', '1', '1')]


## REGULAR EXPRESSION FLAGS

* Most regular expression functions in the re module can take an
optional flags argument. Flags allow us to change the way the parser interprets
the regular expressions. There are numerous regular expression flags,
including:
* re.M or re.MULTILINE - The start and end of string anchors will also match
newlines
* re.S or re.DOTALL - The dot metacharacter will also match a newline.
* re.I or re.IGNORECASE - Matches on alphabetic characters will be case-
insensitive.

In [375]:
import re
s = 'The quick brown fox jumped over the lazy dog'
find = re.findall('the', s)
print(find)

['the']


In [377]:
find = re.findall('the', s, re.IGNORECASE)
print(find)

['The', 'the']


# NATURAL LANGUAGE PROCESSING

The Natural Language Toolkit (NLTK) is a powerful Python library for natural
language processing. It offers an extensive set of functions for processing natural
language content, such as:
* Word / Sentence Tokenisation;
* Synonyms, antonyms and homonyms;
* Stemming and lemmatisation;
* Stop-word removal;
* Part of speech tagging;
* Named Entity Recognition;
* Anaphora and cataphora resolution; and
* Word-sense disambiguation.

## INSTALLING NLTK

In [ ]:
# %conda install nltk
# import nltk
# nltk.download()

## NLTK EXAMPLES - TOKENISATION

In [385]:
# from nltk.tokenize import word_tokenize
# sentence = 'We are studying Natural Language Processing'
# print(word_tokenize(sentence))

In [ ]:
# from nltk import ngrams
# trigrams = ngrams(sentence.split(), 3)
# for grams in trigrams :
#     print(grams)

## NLTK EXAMPLES - POS TAGGING

In [ ]:
# from nltk import pos_tag, word_tokenize
# sentence = 'They agreed the subjects they studied were difficult'
# pos_tagged = pos_tag(word_tokenize(sentence))
# for tag in pos_tagged:
#     print(tag)

## NLTK EXAMPLES - STEMMING

In [ ]:
# from nltk.tokenize import word_tokenize
# from nltk.stem import PorterStemmer
# sentence = 'They agreed the subjects they studied were difficult'
# stemmer = PorterStemmer()
# for word in word_tokenize(sentence) :
#     print(stemmer.stem(word))

## NLTK EXAMPLES - LEMMATISATION

In [ ]:
# from nltk import word_tokenize, pos_tag
# from nltk.stem import WordNetLemmatizer
# sentence = 'They agreed the subjects they studied were difficult'
# lemmatiser = WordNetLemmatizer()
# for word, tag in pos_tag(word_tokenize(sentence)):
#     tag = tag.lower()[0] if tag.lower()[0] in ['a','r','v','n'] else None
#     print(lemmatiser.lemmatize(word,tag) if tag else word)))

## NLTK EXAMPLES - WORD SENSE

In [ ]:
# from nltk import word_tokenize
# from nltk.wsd import lesk
# sentence = 'She went to the bank to deposit some money'
# print(lesk(word_tokenize(sentence), 'bank', 'n'))

In [ ]:
# from nltk.corpus import wordnet as wn
# for synset in wn.synsets('bank') :
#     print(synset,synset.definition())

# NumPy

## Create numpy array

In [7]:
import numpy as np

In [6]:
myArray = np.array([1,2,3,4,5,6,7,8,9,10])

In [14]:
print(myArray)
print(f'The Length: {len(myArray)}')
print(f'Array Type: {type(myArray)}')

[ 1  2  3  4  5  6  7  8  9 10]
The Length: 10
Array Type: <class 'numpy.ndarray'>


## Create an ndarray

In [17]:
arr0d = np.array(42)
print(arr0d)

42


In [19]:
arr1d = np.array([3,4,5])
print(arr1d)

[3 4 5]


In [23]:
arr2d = np.array([[3,4,5], [6,7,8]])
print(arr2d)

[[3 4 5]
 [6 7 8]]


In [25]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [27]:
arr5d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]], ndmin=5)
print(arr5d)

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]


## Numpy datatypes

In [30]:
arr2d = np.array([[3,4,5],[6,7,8]], dtype='f')
print(arr2d)

[[3. 4. 5.]
 [6. 7. 8.]]


In [32]:
print(arr2d.dtype)

float32


In [34]:
print(arr2d.dtype.itemsize)

4


Numpy is not limited to the built-in datatypes. We can define out own vompound types using the built-in types.

In [7]:
salesTransactionType = np.dtype([
    ('itemName', np.str_, 40),
    ('quantity', np.int32),
    ('price', np.float32)
])

In [9]:
print(salesTransactionType)

[('itemName', '<U40'), ('quantity', '<i4'), ('price', '<f4')]


In [24]:
salesitems = np.array([
    ('Apples', 10, 1.20),
    ('Pears', 5, 1.40),
    ('Oranges', 2, 1.30),
], dtype = salesTransactionType)

In [26]:
print(salesitems)

[('Apples', 10, 1.2) ('Pears',  5, 1.4) ('Oranges',  2, 1.3)]


# NumPy Methods

* Slicing
* Stacking
* Reshaping
* Splitting
* Conversion to other datatypes

## Slicing

Slicing in two dimentions <i>i</i> (rows) and <i>j</i> (columns) takes from:
<b>arrayName[ i , j ]</b>

In [36]:
arr2d = np.array([[3,4,5],[6,7,8],[9,10,11]])

In [38]:
print(arr2d[1:3,2])

[ 8 11]


In [57]:
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9], 
        [10,11,12]
    ]
])

In [59]:
'''
Second matrix, first row, 2nd and 3rd values
'''
print(arr3d[1,0,1:3])

[8 9]


In [63]:
'''
Full Slice
'''
print(arr3d[:,0,1:3])

[[2 3]
 [8 9]]


## Stacking

In [66]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [68]:
print(np.stack((a1, a2), axis=0))

[[1 2 3]
 [4 5 6]]


In [70]:
print(np.stack((a1, a2), axis=1))

[[1 4]
 [2 5]
 [3 6]]


## Splitting

Splitting an ndarray breaks it up in to multiple sub-arrays.
NumPy's <i>split()</i> function splits an array into <i>n</i> equally-sized sub-arrays, with <i>n</i> being specified as second argument to the function. Note that the number of elements in original array must be evenly divisible by <i>n</i>.<i></i>

In [9]:
# Must use try-except here

arr1d =  np.arange(12)
print(arr1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
# Split arr1d which is 12 digits long into 4 parts

np.split(arr1d, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [15]:
#  No need for try-except

arr1d = np.arange(14)
print(arr1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [17]:
# Split arr1d into 4 parts, but this array contains only 14

np.array_split(arr1d,4)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10]),
 array([11, 12, 13])]

NumPy's array <i>hsplit()</i> function sllits an array into multiple sub-arrays in a column-wise manner (horizontally).

In [20]:
arr2d = np.array([[1,2], [3,4], [5,6], [7,8]])
np.hsplit(arr2d, 2)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

# Dealing with *NA* Values

Missing data is defined as the values or data that is not stored (or not present) for some variables in the given dataset.

## 3 Primary types:

+ Category
1. Missing completely at Random (MCAR) - you don't know and cannot guess
2. Missing at Random (MAR) - you can guess this value based on values around it
3. Missing Not at Random (MNAR) - you clearly see what value is missing

* Treatment

1. Deleting [ Rows or Columns ]
2. Imputation [ Single or Multiple ]
3. Improve or Sensitize [ Find Data or Best/Worst Case ]

### 1. Deleting

One way to handle missing data is to simply remove rows or columns with mossing values.

In [41]:
import pandas as pd
import numpy as np

# Create a small dataset with missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, np.nan, 22, 29],
    'Gender': ['F', 'M', 'M', 'M', np.nan],
    'Salary': [50000, 60000, 55000, np.nan, 52000]
}

# Create a DataFrame
dataset_Test = pd.DataFrame(data)

# Display the dataset
dataset_Test

Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  30.0      M  60000.0
2  Charlie   NaN      M  55000.0
3    David  22.0      M      NaN
4      Eva  29.0    NaN  52000.0

In [43]:
# This will remove all rows where one or more missing data

working_data_after_del = dataset_Test.dropna()
print("Test - Deletion of Missing Data:")
working_data_after_del

Test - Deletion of Missing Data:


Name   Age Gender   Salary
0  Alice  25.0      F  50000.0
1    Bob  30.0      M  60000.0

### 2. Imputation

#### Using Mean/Median ============================

* Replace missing values with central tendency

Replace missing values with the mean (for normally distributed data) or median (for skewed data) of the non-missing values in the same column.

* dataframe.fillna(Train.mean())

In [56]:
import pandas as pd
import numpy as np

# Create a small dataset with missing values
data = {
    'Feature1': [10, 20, np.nan, 40, 50],
    'Feature2': [7.5, np.nan, 15.0, np.nan, 12.0],
    'Feature3': [100, 200, 300, 400, np.nan]
}

# Create the DataFrame named Train
Train = pd.DataFrame(data)

# Display the dataset
print("Train Dataset:")
print(Train)

# Now, use mean imputation on the missing values
df_mean_impute = Train.fillna(Train.mean())

# Display the imputed dataset
print("\nDataset after mean imputation:")
print(df_mean_impute)


Train Dataset:
   Feature1  Feature2  Feature3
0      10.0       7.5     100.0
1      20.0       NaN     200.0
2       NaN      15.0     300.0
3      40.0       NaN     400.0
4      50.0      12.0       NaN

Dataset after mean imputation:
   Feature1  Feature2  Feature3
0      10.0       7.5     100.0
1      20.0      11.5     200.0
2      30.0      15.0     300.0
3      40.0      11.5     400.0
4      50.0      12.0     250.0


#### Using Mode ============================

* For categorical data, replace missing values with the mode  (the most frequent category) in the same column.

> For example:
In a survey dataset, if a question about favorite colors has missing values, replace them with the most common color choice.

* dataframe.fillna(df.mode().iloc[0])

In [65]:
import pandas as pd
import numpy as np

# Create a small dataset with missing values in the 'Favorite Color' column
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Favorite Color': ['Blue', 'Green', np.nan, 'Blue', np.nan]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the dataset
print("Original Dataset:")
print(df)

# Use mode imputation to fill missing values with the most common color
df_mode_impute = df.fillna(df.mode().iloc[0])

# Display the dataset after mode imputation
print("\nMethod 3 - Mode Imputation:")
print(df_mode_impute)


Original Dataset:
      Name Favorite Color
0    Alice           Blue
1      Bob          Green
2  Charlie            NaN
3    David           Blue
4      Eva            NaN

Method 3 - Mode Imputation:
      Name Favorite Color
0    Alice           Blue
1      Bob          Green
2  Charlie           Blue
3    David           Blue
4      Eva           Blue


#### Using Regression ============================

* Use regression models to predict missing values based on the relationships with other variables in the dataset.
  > Example:
  In a dataset of housing prices, you can use regression to predict the missing price of a house based on factors like square foorage and location.

imputer = KNNimputer(n_neighbors=5) # use K-nearest neighbors for imputation
imputed_data = imputer.fit_transform(data)
imputed_dataset.append(pd.DataFrame(imputed_data, columns=data.columns))

In [75]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

# Create a small dataset with some missing values
data = {
    'SquareFootage': [1500, 2000, 1700, np.nan, 2500],
    'LocationScore': [8, 7, 9, 6, np.nan],  # Representing desirability of location
    'Price': [300000, 450000, np.nan, 600000, 500000]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Display the dataset with missing values
print("Original Dataset with Missing Values:")
print(df)

# Initialize KNNImputer with 5 neighbors
imputer = KNNImputer(n_neighbors=5)

# Perform KNN imputation
imputed_data = imputer.fit_transform(df)

# Convert imputed data back into a DataFrame with original column names
imputed_dataset = pd.DataFrame(imputed_data, columns=df.columns)

# Display the dataset after imputation
print("\nDataset after KNN Imputation:")
print(imputed_dataset)


Original Dataset with Missing Values:
   SquareFootage  LocationScore     Price
0         1500.0            8.0  300000.0
1         2000.0            7.0  450000.0
2         1700.0            9.0       NaN
3            NaN            6.0  600000.0
4         2500.0            NaN  500000.0

Dataset after KNN Imputation:
   SquareFootage  LocationScore     Price
0         1500.0            8.0  300000.0
1         2000.0            7.0  450000.0
2         1700.0            9.0  462500.0
3         1925.0            6.0  600000.0
4         2500.0            7.5  500000.0


#### Use Domain Knowledge ============================

Utilixe domain knowledge or expert input to estimate missing values, especially when no statistical method is suitable.
> Example:
In an agricultural study, if sensor data is missing for a specific day, consult an agronomist to estimate the likely values based on weather conditions and crop growth.

In [88]:
import pandas as pd
import numpy as np

# Create a small dataset with missing Rainfall values
data = {
    'Day': ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'],
    'Temperature': [30, 32, 29, 31, 33],  # Temperature in degrees Celsius
    'Rainfall': [5, np.nan, 7, np.nan, 10],  # Rainfall in mm, with missing values
    'CropYield': [1200, 1150, 1180, 1175, 1230]  # Crop yield in kg/hectare
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Display the dataset with missing Rainfall values
print("Original Dataset with Missing Values:")
print(df)

# Expert Input (agronomist's estimate based on knowledge of weather and crops)
# For example, the agronomist might say:
# - On 'Day 2', it was overcast, so it's estimated that 4 mm of rain likely fell.
# - On 'Day 4', conditions were dry but irrigation was applied, so it's estimated to be 8 mm.

# Manually filling the missing values using expert input
df.loc[df['Day'] == 'Day 2', 'Rainfall'] = 4  # Agronomist estimate for Day 2
df.loc[df['Day'] == 'Day 4', 'Rainfall'] = 8  # Agronomist estimate for Day 4

# Display the dataset after expert-based imputation
print("\nDataset after Expert Input Imputation:")
print(df)


Original Dataset with Missing Values:
     Day  Temperature  Rainfall  CropYield
0  Day 1           30       5.0       1200
1  Day 2           32       NaN       1150
2  Day 3           29       7.0       1180
3  Day 4           31       NaN       1175
4  Day 5           33      10.0       1230

Dataset after Expert Input Imputation:
     Day  Temperature  Rainfall  CropYield
0  Day 1           30       5.0       1200
1  Day 2           32       4.0       1150
2  Day 3           29       7.0       1180
3  Day 4           31       8.0       1175
4  Day 5           33      10.0       1230


#### Creating a 'Missinngness' Feature  ============================

* Treating Missingness as an Informational Variables

* Instead of imputing, crate a new binary variable indicating wherher data was missing in a specific column.
> Example
In a customer dataset, inrtoduce a 'Missing Phone Number' variable to capture whether phone numbers were provided or not.

df['Missinnng_B'] = df['B'].isna().astype(int)

In [99]:
import pandas as pd
import numpy as np

# Create a small dataset with missing values in 'PhoneNumber'
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'PhoneNumber': ['123-456', np.nan, '789-012', np.nan, '345-678'],
    'Email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'david@example.com', 'eva@example.com']
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Display the original dataset
print("Original Dataset:")
print(df)

# Create a new 'Missing_PhoneNumber' column indicating if 'PhoneNumber' is missing
df['Missing_PhoneNumber'] = df['PhoneNumber'].isna().astype(int)

# Display the dataset with the new "Missingness" feature
print('\nCreating a "Missingness" Feature:')
print(df)


Original Dataset:
      Name PhoneNumber                Email
0    Alice     123-456    alice@example.com
1      Bob         NaN      bob@example.com
2  Charlie     789-012  charlie@example.com
3    David         NaN    david@example.com
4      Eva     345-678      eva@example.com

Creating a "Missingness" Feature:
      Name PhoneNumber                Email  Missing_PhoneNumber
0    Alice     123-456    alice@example.com                    0
1      Bob         NaN      bob@example.com                    1
2  Charlie     789-012  charlie@example.com                    0
3    David         NaN    david@example.com                    1
4      Eva     345-678      eva@example.com                    0


#### Forward and Backward Filling  ============================

* Use forward filling (carrying the last known value forward) or backward filling (using the next known value) to impute missing values in time series data.
  > Example:
In a stock price daset, use forward filling to fill in missing daily prices with the last known value.

* df_forward_fill = df.ffill() - take sample from below NA value
* df_backward_fill = df.bfill() - take sample from above NA value

In [105]:
import pandas as pd
import numpy as np

# Create a small time series dataset with missing values
data = {
    'Date': pd.date_range(start='2023-10-01', periods=5, freq='D'),
    'StockPrice': [100, np.nan, 102, np.nan, 105]  # Stock prices with some missing values
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Display the original dataset
print("Original Dataset:")
print(df)

# Forward fill to carry the last known value forward
df_forward_fill = df.ffill()

# Backward fill to use the next known value
df_backward_fill = df.bfill()

# Display the results
print("\nForward Filling:")
print(df_forward_fill)

print("\nBackward Filling:")
print(df_backward_fill)


Original Dataset:
        Date  StockPrice
0 2023-10-01       100.0
1 2023-10-02         NaN
2 2023-10-03       102.0
3 2023-10-04         NaN
4 2023-10-05       105.0

Forward Filling:
        Date  StockPrice
0 2023-10-01       100.0
1 2023-10-02       100.0
2 2023-10-03       102.0
3 2023-10-04       102.0
4 2023-10-05       105.0

Backward Filling:
        Date  StockPrice
0 2023-10-01       100.0
1 2023-10-02       102.0
2 2023-10-03       102.0
3 2023-10-04       105.0
4 2023-10-05       105.0
